@Library('jenkins-shared-library') _

serviceBuildTest(
    serviceName: 'payment',
    runtimeService: 'payment',
    testService: 'payment-tests',
    startDeps: ['postgres', 'rabbit', 'product', 'order'],
    reportGlob: 'reports/payment/junit.xml',
    sonarEnabled: true,
    trivyEnabled: true,
    sonarProjectKey: 'micro-ecom-auth',
    sonarProjectName: 'micro-ecom-auth',
    sonarSources: 'src',
    sonarExtraArgs: '-Dsonar.javascript.lcov.reportPaths=coverage/lcov.info'
)