@Library('jenkins-shared-library') _

PipeLine(
    serviceName: 'notification',
    runtimeService: 'notification',
    testService: 'notification-tests',
    startDeps: ['postgres', 'rabbit'],
    reportGlob: 'reports/notification/junit.xml',
    sonarEnabled: true,
    trivyEnabled: true,
    sonarProjectKey: 'micro-ecom-notification',
    sonarProjectName: 'micro-ecom-notification',
    sonarSources: 'src',
    sonarExtraArgs: '-Dsonar.javascript.lcov.reportPaths=coverage/lcov.info'
)