@Library('jenkins-shared-library') _

serviceBuildTest(
    serviceName: 'order',
    runtimeService: 'order',
    testService: 'order-tests',
    startDeps: ['postgres', 'rabbit', 'product'],
    reportGlob: 'reports/order/junit.xml',
    sonarEnabled: true,
    trivyEnabled: true,
    sonarProjectKey: 'micro-ecom-auth',
    sonarProjectName: 'micro-ecom-auth',
    sonarSources: 'src',
    sonarExtraArgs: '-Dsonar.javascript.lcov.reportPaths=coverage/lcov.info'
)